i think the subtitles are fine but your vidstack implementation is wrong,  check this docs from vidstack and fix it so subtitles can load :-
API

Text Tracks
An overview of using and configuring text tracks (captions/subtitles).

Loading
Section titled Loading
The Loading Text Tracks guide covers how to initialize tracks and supported formats/kinds.

Tracks List
Section titled Tracks List
The read-only textTracks property on the player returns a TextTrackList object that contains TextTrack objects. Keep in mind the mentioned objects are custom implementations and not the browser’s native classes.

The returned list is live; that is, as tracks are added to and removed from the player, the list’s contents change dynamically. Once you have a reference to the list, you can monitor it for changes to detect when new tracks are added or existing ones are removed by listening to list events.

// Length
const hasItems = player.textTracks.length;

// Index
const track = player.textTracks[0];

// Get by ID
const track = player.textTracks.getById('...');

// Iterating
for (const track of player.textTracks) {
}

// Map to array
player.textTracks.toArray();
List Events
Section titled List Events
The TextTrackList object is an EventTarget which dispatches the following events:

add: Fired when a text track has been added to the list.
remove: Fired when a text track has been removed from the list.
mode-change: Fired when the mode of any text track has changed.
player.textTracks.addEventListener('add', (event) => {
  const newTrack = event.detail; // `TextTrack`
  // ...
});

player.textTracks.addEventListener('mode-change', (event) => {
  const track = event.detail; // `TextTrack`
  // ...
});
Managing Tracks
Section titled Managing Tracks
Add Tracks
Section titled Add Tracks
Text tracks can be dynamically added and removed like so:

import { MediaPlayer, MediaProvider, Track } from '@vidstack/react';

<MediaPlayer>
  <MediaProvider>
    <Track
      src="/media/subs/english.vtt"
      kind="subtitles"
      label="English"
      lang="en-US"
      type="vtt"
      default
    />
  </MediaProvider>
</MediaPlayer>
You can also create tracks and add them programtically like so:

import { TextTrack } from '@vidstack/react';

const track = new TextTrack({
  src: '/media/subs/english.vtt',
  kind: 'subtitles',
  label: 'English',
  language: 'en-US',
  type: 'vtt',
  default: true,
});

track.addCue(new VTTCue(0, 10, 'Hello world!'));

player.textTracks.add(track);
Remove Tracks
Section titled Remove Tracks
Text tracks can be removed programtically like so:

player.textTracks.remove(track);
All text tracks can be removed by calling clear():

player.textTracks.clear();
Track Mode
Section titled Track Mode
The mode property of a text track accepts the following values:

showing: Track will load, receive cue updates, and is visible on-screen.
hidden: Track will load, receive cue updates, but is not visible on-screen.
disabled: Track will not load and it will not receive cue updates.
textTrack.mode = 'showing';
Only one track per kind can have a mode of showing. Other tracks of the same kind that are specifically showing will have their mode set to disabled on change.

Track Events
Section titled Track Events
The TextTrack object is an EventTarget which dispatches the following events:

load-start: Fired when the track begins loading.
load: Fired when the track has finished loading and parsing.
error: Fired when there is a critical error loading or parsing the track.
add-cue: Fired when a new cue has been added.
remove-cue: Fired when a cue has been removed.
cue-change: Fired when the active cues has changed.
mode-change: Fired when the mode has been changed.
track.addEventListener('load-start', () => {
  // ...
});

track.addEventListener('load', () => {
  // ...
});

track.addEventListener('error', () => {
  // ...
});

track.addEventListener('cue-change', () => {
  // active cues changed
});
Media State
Section titled Media State
The following text track related properties are available on the media store:

textTracks: An array containing the current list of TextTrack objects.
textTrack: The current captions/subtitles TextTrack object or null if none is showing.
import { useRef } from 'react';

import { MediaPlayer, useMediaStore, type MediaPlayerInstance } from '@vidstack/react';

function Player() {
  const player = useRef<MediaPlayerInstance>(null);

  const { textTracks, textTrack } = useMediaStore(player);

  return <MediaPlayer ref={player}>{/* ... */}</MediaPlayer>;
}
INFO
If you’re using React check out the useCaptionOptions hook for building menus.

Remote Control
Section titled Remote Control
The changeTextTrack method on the media remote can be used to dispatch media-text-track-change-request request events to update the current audio track like so:

// Set mode of text track in list at index 0.
remote.changeTextTrackMode(0, 'showing');
Media Events
Section titled Media Events
The following text track related events are available on the player:

import {
  MediaPlayer,
  type MediaTextTrackChangeEvent,
  type MediaTextTracksChangeEvent,
  type TextTrack,
} from '@vidstack/react';

function Player() {
  function onTextTracksChange(tracks: TextTrack[], nativeEvent: MediaTextTracksChangeEvent) {
    // ...
  }

  function onTextTrackChange(track: TextTrack | null, nativeEvent: MediaTextTrackChangeEvent) {
    // ...
  }

  return (
    <MediaPlayer onTextTracksChange={onTextTracksChange} onTextTrackChange={onTextTrackChange}>
      {/* ... */}
    </MediaPlayer>
  );
}