vercel deployment showing this build error fix it:-
npm error
npm error Conflicting peer dependency: firebase@11.7.3
npm error node_modules/firebase
npm error   peer firebase@"^11.3.0" from @tanstack-query-firebase/react@1.0.6
npm error   node_modules/@tanstack-query-firebase/react
npm error     @tanstack-query-firebase/react@"^1.0.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /vercel/.npm/_logs/2025-05-19T15_56_05_292Z-eresolve-report.txt
npm error A complete log of this run can be found in: /vercel/.npm/_logs/2025-05-19T15_56_05_292Z-debug-0.log
Error: Command "npm install" exited with 1
Exiting build container